### ISSUE TITLE
Section 2.3 - Live Content Playback

### ISSUE THREAD

**Issue by thasso** [w3c/webmediaguidelines#14]
This section should follow the basic structure already described in 2.2 and highlight the following: 

 * Content-Generation and the differences compared to VoD content
 * Content-Delivery for Live content
 * Content-Playback: How to Manifest updates work and how is/can the currentTime be reported by the player

The following use-cases might be interesting to highlight:
 * Reduce live edge latency
 * Server side Ad insertion

**Comment by joelkorpi** [comment]
I think perhaps we should also differentiate between live streaming delivery through real-time protocols like WebRTC and RTMP vs. delivery via HTTP (which is "near-live" but delayed because of the chunking in most setups).
