### ISSUE TITLE
Charts/graphs/visual aids for guidelines

### ISSUE THREAD

**Issue by joelkorpi** [w3c/webmediaguidelines#18]
I think we could benefit from some visual aids to accompany some of the sections. Specifically when talking about content workflows regarding content delivery and adaptive streaming, I find it useful to include a visual aid. Do you or does your company have such visual aids that already exist that we could use?

Specifically, sections 2.4, 2.5, and 2.7 I believe would greatly benefit from this.

Here's an example of the style of chart I'm referring to (ignore the content of it):

![image](https://user-images.githubusercontent.com/10716543/28547078-34661010-709b-11e7-8eb6-a71580125329.png)

**Comment by andybeach** [comment]
I think we might have some - I’ll have a look this week.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by joelkorpi** [comment]
@andybeach were you able to find any visual aids?

**Comment by thasso** [comment]
I'd propose to close this one since we don't seem to get visuals in time.

**Comment by thasso** [comment]
I move this to Milestone v2 and we can take another look at it for the next version
