### ISSUE TITLE
VOD Uses cases 2.2

### ISSUE THREAD

**Issue by edwardmhunton** [w3c/webmediaguidelines#19]
I will add content for the other vod uses cases as listed at the foot of the 2.2 section. Let me know if you already have material for these.

**Comment by joelkorpi** [comment]
Thank you Edward. Just for clarity, you're referring to completing sections 2.8 and 2.10, correct?

A few other thoughts I had are:
 1. Should we move the VOD sections so that they are subsequent in the document?
 2. Should we add a use case for AVOD and/or SVOD?

**Comment by edwardmhunton** [comment]
No, the missing bits of 2.2 is what I am refereeing to.

“Other possible VOD use cases

  *   Buffer manipulation (device / storage dependent)
  *   HTTP byte range requests
  *   HTTPs support
  *   Player event exposure
  *   HDCP security requirement for HDMI
  *   Watermarking
  *   Hardware acceleration support
“


The other bits I have written are 3.1 and 3.4

ed

--
Edward Hunton
Video Player Developer, Core Platform Technology
Sky
Edward.hunton@sky.uk<mailto:Edward.hunton@sky.uk>

**Comment by edwardmhunton** [comment]
Hi Joel

How are we making a distinction between live streaming and live linear streaming? 2.3 / 2.6

Also, I have written material for client-side ad insertion but it’s in VOD use-cases. There’s no need to duplicate this?

ed

--
Edward Hunton
Video Player Developer, Core Platform Technology
Sky
Edward.hunton@sky.uk<mailto:Edward.hunton@sky.uk>

**Comment by joelkorpi** [comment]
Good question. I think we can delete "live linear" as it's redundant.

For the ad insertion side, I recommend we mention all ad insertion in a single section. @edwardmhunton

**Comment by joelkorpi** [comment]
We are tracking this issue related to ad-insertion here: https://github.com/w3c/webmediaguidelines/issues/28
