### ISSUE TITLE
secion 5 for Application Structure

### ISSUE THREAD

**Issue by boyofgreen** [w3c/webmediaguidelines#20]
I'll be starting a new section that addressing the application structure to include browser apps, PWAs, Hosted Web Apps, Chrome Embedded Framework etc.  My target will be to deliver v1 for first week of august.
  Replay if you have any ideas for content for this section that I can write up, but basic structure as I see it now:
Web App Structure
-Intro
-Web App Content management approaches
  - Hosted 
  - Packaged
- Web App Runtime Environments
   - Browser
   - App Store containers
   - CEF
Progressive Web Apps
  - Requirements
  - Use Cases
  - Advantages for Media Applications
   - Avaliability

**Comment by joelkorpi** [comment]
Looks great! Excited to see the first draft.

**Comment by boyofgreen** [comment]
Please provide feedback, I know there are a number of link out opertunities I need to add in as well.

# Web App Structure

Media companies more and more are making their content and channels available where ever users are consuming media.  More often than not this includes the web and native app platforms.  As we see rise in media companies using web technologies to build cross platform apps (that stretch across the web and native app platforms) it becomes more important to define clarify the different approaches you can take to building "apps" with web technologies.

## Web App Content management approaches

The easiest way to delineate between the types of Web apps are by how we manage the content inside them. In the case of traditional applications and mobile apps, the entire application is downloaded from the store and then ran locally. In web terms. In contrast, a website keeps all of its content on the server and then when the pages loader. It brings the entire application down into the browser. The same approaches are utilized with web content inside of the app space there often known as packaged web apps and hosted web apps. 

### The Packaged App

The Packaged App is a type of web app that distributed in its entirety to a user through a single download. Generally, we see packaged apps within App Markets. Packaged Apps have these characters:

- Downloaded in entirety through a store or market
-  Generally offline by default, as all the code is living on the users device
- Retrieve data from the internet via services similar to native apps. generally called via ajax

Some Markets, such as Window Store and Amazon App Store enable you to submit packaged apps directly to the market without the need of any external packaging tools. These markets also expose additional APIs for packaged apps that aren’t available to apps via the browser. Other markets, such as iOS App Store and Android Play require a third party utility such as Cordova or cross walk to enable packaged web apps. 

### The Hosted App

Hosted Apps are web apps submitted to app markets that point to web content that remains on the webserver as appose to being packaged and submitted to the store. Hosted app’s have these Characteristics:

- Have a thin layer of native code, usually containing a webview and / or an app manifest that is submitted to the market
- Can run dynamic web content from web server (thank asp.net PHP, etc).
- By default have no functionality when device is offline (just like web)
- Hosted web apps are updated on the web server instead of pushing packages to the app store.

### Progressive Web Apps

Progressive web apps or PWAs has become the de facto app format for the web. Just like hosted web apps, progressive web apps load their content from the server when the app is opened. However, Progressive Web apps also can store this web app locally through a new technology called service workers, which allows progressive web apps to bridge across both the benefits of package web apps and hosted web apps.  Some platforms run PWAs in the browser while others (like android and Windows 10) run PWAs in a stand along app container.  You can learn more about building progressive web apps here.  

## Web Based Platforms

Some platforms such as web OS are themselves a web based environment, meaning all applications in that environment or built with the web. And run as independent applications within the environment just like a web page may run inside of a web browser.  TV manufacturers, sometimes use chromium, as a basis for a web based platform on media device that allows web apps to run as standalone applications. 

## Web App Containers

Delivering the Web app on the platform is not a trivial task as each platform may have a different approach on how a web app is delivered to a user. Some platforms such as Xbox (windows 10) and Play station give the Web apps their own standalone container, which allows the app to be downloaded from a store and ran independently of a browser.

### Mobile App Containers

For a Web app to be distributed through the store on platforms like iOS and Android, an app container needs to be used. popular app containers such as Cordova and cross walk are used by web developers to deliver a web app through a store.  This approach often adds over head to the application as the web app is rendered in a webview or the app may contain the entire browser runtime within each app container. 

### Chrome Imbedded Framework and Electron

In desktop environments, we see the use of electron and Chrome Imbedded Framework (CEF) to deliver web apps as desktop applications.  CEF and Electron uses the open source version of chrome as a runtime environment for the application. Much like we see one mobile platforms, this approach has additional overhead as instead of using the native rendering engine of the platform, chromium is delivered inside each application to render the web app. This gives the Web app additional privileges to access native API’s, but at the same time raises many security concerns. 

## Use Cases

**Comment by joelkorpi** [comment]
Great outline Jeff! Fantastic start. I don't see any major issues. Mostly just the obvious stuff you're probably already aware of:

1. Feel like the "Web Based Platforms" sections needs more depth. Maybe a link to a sample app.
2. I suggest a diagram to show how Web Apps and their associated container and delivery mechanisms work together.
3. Excited to see the use cases fleshed out

**Comment by joelkorpi** [comment]
This PR has been merged!
