### ISSUE TITLE
Create a dedicated Section for Ad-Insertion

### ISSUE THREAD

**Issue by thasso** [w3c/webmediaguidelines#28]
As mentioned in #19, we should maybe consolidate all Ad-Insertion related topics in one section?

**Comment by joelkorpi** [comment]
Agree. Maybe let's move it to section 3?

**Comment by joelkorpi** [comment]
@thasso Where did we end up on this? Are you going to move these sections?

**Comment by thasso** [comment]
I created PR #33 with this. I did follow you suggestion and moved it to section 3

**Comment by joelkorpi** [comment]
Closed
