### ISSUE TITLE
Scope of media streaming/playback use cases

### ISSUE THREAD

**Issue by squapp** [w3c/webmediaguidelines#3]
What are your thoughts on the scope of media streaming and playback use cases?

For example, let's take 2.1 On-Demand Streaming:
Does the code sample include a Manifest file (DASH/HLS)? I think it should, otherwise there will be difference to 2.2 Live Streaming, because the same segments can be used for on-demand and live.

Is it an accessible Manifest file (e.g. referencing segments that are hosted somewhere)? This would mean accessing existing or new DASH/HLS test vectors and making sure that they are available, which might be difficult (for live streaming)

What about MSE/EME code samples? Both [EME](https://www.w3.org/TR/encrypted-media/#examples) and [MSE](https://www.w3.org/TR/media-source/#examples) provide code samples in the specifications. Web Media guidelines could just reference these or go further and provide actual test vectors with the code samples.

**Comment by michelnev** [comment]
Regarding MSE/EME: Thinking about this from a developer's perspective, I would like to see code samples.   I would also expect to have a way to test the code, so, yes, test vectors are a must.

**Comment by squapp** [comment]
I will try to come up with different options for code samples. That should make it easier to decide

**Comment by joelkorpi** [comment]
With regards to the manifest, the proposed decision is: WAVE should maintain a pool of “gold-standard, known-good” manifest-level content produced and/or blessed by DASH-IF and Apple that can be referenced for testing, etc.

If there's an additional issue for MSE/EME let's open another issue for that.

**Comment by joelkorpi** [comment]
Issue has been closed
