### ISSUE TITLE
Merge sections about Thumbnails

### ISSUE THREAD

**Issue by thasso** [w3c/webmediaguidelines#30]
We should merge sections about thumbnails and do not explicitly differentiate between live and VoD use cases.
The only difference from the players perspective is how to get updates in case of live and it is not clear yet how this will be done in HLS or DASH.

**Comment by joelkorpi** [comment]
Agreed!

**Comment by joelkorpi** [comment]
@thasso Are you going to be able to submit this section by tomorrow? If not, I'll remove it.

**Comment by thasso** [comment]
I pushed an initial version in PR #34

**Comment by joelkorpi** [comment]
Closed
