### ISSUE TITLE
addition of developer "best practices" statement to document

### ISSUE THREAD

**Issue by boyofgreen** [w3c/webmediaguidelines#4]
I'd like to propose a new section to the document that clarifies our support for common Web Development best practices.  I think this could be it’s own section, or it can be a section of the introduction (I’m leaning towards a section of the introduction).  Here are my thoughts:

This document is squarely aimed at support developers who are building Media based web applications.  For that reason the focus on the content is around specific media-centric APIs and app scenarios.  This however does not preclude our support for web development best practices. 
Many of the APIs we highlight in this documentation relay on modern web developer techniques.  For example, not all browser support Encrypted Media Extensions, so a [feature detection](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Feature_detection) would need to be implemented:  
```
if (!video.mediaKeys) {
      navigator.requestMediaKeySystemAccess('org.w3.clearkey', [
        { initDataTypes: ['webm'],
          videoCapabilities: [{ contentType: 'video/webm; codecs="vp8"' }] }
    …
}
```
 This allows a developer to implement EME when supported, and not execute code that will generate errors in browsers that do not.  Another important practice is the use of [polyfills](https://developer.mozilla.org/en-US/docs/Glossary/Polyfill) which in many cases can provide an alternative functionality when the browser doesn’t natively support a feature.
  In general, best practices for modern web development are well documented across the web.  A great place to start to familiarize yourself with these is practices is the  Mozilla [Cross browser testing guide](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing).

**Comment by mavgit** [comment]
I think that, likewise, we should have a reference to these developer guidelines in the "Web Media APIs 2017" spec. I see the Web Media APIs 2017 spec as targeted at device platform developers, not app developers. But it would make sense to point from Web Media APIs 2017 to this document for readers of Web Media APIs 2017 who are app developers. Make sense?

**Comment by boyofgreen** [comment]
I agree, we want to be clear in both documents who the audience is for that document.  We should link the docs so the right audiences get to the right doc.  When I turn this into a PR, I'll add text and links in for that.

**Comment by squapp** [comment]
> This allows a developer to implement EME when supported, and not execute code that will generate errors in browsers that do not

For this particular example, we could also reference existing/working code from open source players, e.g. [dash.js](https://github.com/Dash-Industry-Forum/dash.js/blob/development/src/streaming/protection/Protection.js) 
It also handles different versions of EME that can be found on various platforms

**Comment by joelkorpi** [comment]
I agree, we should have a best practices section as well as an introduction describing the target audience (with links to Web Media APIs 2017). I can also obviously provide examples for use with JW Player and any other open source video player.

**Comment by boyofgreen** [comment]
that makes sense.  I am going to put this into a PR, but I would be happy to have one of you update the sample.

**Comment by joelkorpi** [comment]
This was discussed today at the F2F and the concern was brought up that we want to produce code examples that have the longest shelf life possible and do not want to increase the scope of these guidelines to move beyond a few examples. Describing best practices for every technology/standard/format/codec would expand the scope of the guidelines beyond our initial target.

I propose that we include examples and a best practices section, as suggested, but limit it to psuedo-code or limited examples to cover the main important best practices.

**Comment by joelkorpi** [comment]
Issue has been closed
