### ISSUE TITLE
Guidelines may want to consider additional sections to cover targeting TV, mobile & PC devices.

### ISSUE THREAD

**Issue by mavgit** [w3c/webmediaguidelines#45]
Previous W3C specs provided guidance for developers targeting mobile devices. [Mobile Web Application Best Practices](https://www.w3.org/TR/mwabp/) includes useful guidance for web app developers targeting mobile devices related to data usage, resource usage, security, privacy, device detection, etc.

Web media apps need to run on PC, mobile and TV devices, each of which have differences in screen size, user interface, viewing distance, etc. Perhaps the Web Media API Guidelines could include some similar guidance extended from mobile to PC, mobile and TV devices.

**Comment by joelkorpi** [comment]
Hi Mark, Would this be more applicable to the integration spec? We could certainly add best practices here as well, just want to make sure it's in the right place.

**Comment by mavgit** [comment]
No, this is not a browser integration spec. It's an application spec. Dealing with these issues is too large a change to the spec for now.

**Comment by joelkorpi** [comment]
Ok let's add this to milestone v2. Does that sound good? @mavgit @thasso

**Comment by thasso** [comment]
Sounds good to me. I created two Milestones, v1 and v2 and I moved this one to v2.
