### ISSUE TITLE
Section 2 Feedback Continued Through 2.9.1

### ISSUE THREAD

**Issue by michelnev** [w3c/webmediaguidelines#49]
1. Section 2.7 suggestions: This sentence is unclear, please rephrase: "There are different levels of caching; popular VOD content is kept closer to the edge in the CDN network in this way it can be delivered to customers faster than an edge server that isn't tuned for high volume delivery."   Minor change here: "Older and less popular content is retained in a mid-tier **cache** **while** the long tail content is relegated to a lower tier. "

2. Section 2.8 suggestions: First Paragraph: "As mentioned in the **C**ontent **G**eneration section**,** the player uses a tag within the manifest to determine the playout type. In **HLS,** if there is a type with the value of VOD, the player will not reload the manifest. This has important consequences if there are changes in availability after the session as commenced. In **DASH,** the difference between a live and VOD playlist are more subtle (more detail) "  Do you want to explain the "important consequences" for HLS?  

3. Section 2.8 suggestions: Second Paragraph: End the sentence after "predefined duration."  Change "current time" to "playback position".  Maybe remove "amount and"?

4. Section 2.8 suggestions: Third Paragraph: "Additionally, the UX requirements are different between VOD and linear. Unlike linear content, which lends itself to being browsed within an EPG (electronic program guide), VOD content is typically navigated using tiles or poster galleries. There is also a trick play bar to view the current playback position and seek to other points within the content."

5. Section 2.9 has only one subsection.  Just rename it to VOD Pre-caching and make it one section.

6. Section 2.9 first paragraph (if it remains after previous suggestion): Change "In the previous section,..." to "In the previous **sections**,...".  Change second sentence to "In this section, the use-case is defines an on-demand streaming strategy employed on clients to improve performance."

7. Section 2.9.1 suggestions:
  - First sentence change "...will be the.." to "..is the...".
  - When I read the first sentence, the equation is (% of sessions which buffer)/(length of the session).  Is that the intended equation?
  - In the second sentence, add commas around "as a consequence".
  - Add a citation for the "...10% of users abandon a video stream"?
  - Remove the word "will" from the "...developers will use points...". 
  - End the sentence at "... UX to pre-cache content."  The next sentence starts: "For example, when entering a mezzanine/synopsis page, ..."
  - Maybe rewrite the for example sentence as: "For example, when entering a mezzanine/synopsis page, the application might preemptively cache the content by filling the player’s video buffer or, alternatively, storing the chunks locally."
  - Maybe rewrite the "The consequence..." sentence: "Pre-caching allows the video to commence playing without buffering and provides the user with a more responsive initial playback experience."
  - Minor update to the last sentence: "This technique is not used for cellular sessions where the user’s mobile data would be consumed on content that they do not watch."

**Comment by joelkorpi** [comment]
#2 - 2.8 - elaborate on "more detail" regarding HLS and DASH specifics as mentioned in the section

**Comment by joelkorpi** [comment]
Added call for consensus label as my PR was submitted a while back. Will close out in a few days if no comments. @thasso
