### ISSUE TITLE
Scope clarification for guidelines

### ISSUE THREAD

**Issue by joelkorpi** [w3c/webmediaguidelines#5]
After talking with @thasso today at the F2F, we propose that we should clearly define and limit the scope of v1 of the guidelines to not include superfluous content. I propose that, for example, we  NOT include full player implementation examples with code samples and configurations, but rather we discuss overall guidelines for implementations and link to specific technology implementation guidelines (such as JW Player, etc.).

**Comment by andybeach** [comment]
i noticed the guidelines are missing CC/subtitles.  there will be a lot of requests for clarification on accessibility in the initial draft.

**Comment by joelkorpi** [comment]
@andybeach Great point Andy. I think we should track this as it's own issue as it's very important. Would you mind posting a new issue that we can track this under? I'll make sure it's also included in the scope.

**Comment by thasso** [comment]
I agree with @joelkorpi that keep the first iteration short and focus on the main issues.

**Comment by andybeach** [comment]
Will do

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by joelkorpi** [comment]
Also, as discussed on the weekly call yesterday, in regards to code examples, sample players, and all additional samples: All examples we link to will be stored in a repository that we can link to and also clone and host (within CTA/W3C) if we choose.

**Comment by joelkorpi** [comment]
Proposed scope definition is below. Please comment on any changes @thasso @boyofgreen 

> The scope of this document includes general guidelines, best practices, and examples for building media applications across web browsers and devices. This includes native and browser-based applications as well as integrated and stand-alone devices. The examples in this document provides a starting point to build your media application and includes example implementations from various providers and vendors. This document also includes sample content and manifests as well as encoding guidelines to maximize the provide hints on achieving the best quality and efficiency for your media applications.

**Comment by joelkorpi** [comment]
Additional notes from @mavgit 
"I've always assumed that while WAVE overall applies to both HTML and non-HTML apps (e.g. the content spec) , the two WAVE HATF specs are  of limited application to only HTML apps and have no applicability to non-HTML apps."

**Comment by joelkorpi** [comment]
Issue has been closed
