### ISSUE TITLE
Section 2 Feedback Continued Section 2.10 

### ISSUE THREAD

**Issue by michelnev** [w3c/webmediaguidelines#52]
1. Section 2.10.1 suggestions:
  - Remove the "This is helpful in a few scenarios." sentence.
  - Update the final sentence of the first paragraph to something like: "In the VOD scenario where a user wants to access a specific location in a file, a range request allows the player to access content at a specific location without downloading the entire transport chunk."
  - Second sentence of the second paragraph: "The player needs to be able to playback a source buffer and **the** server must be configured to serve ranges."
  - Changes to the next three sentences: "The exchange begins when a client makes an HTTP HEAD request **. If range requests are supported,** the server responds with a header that includes Accept-Ranges: bytes and the client can issue subsequent requests for partial content."
  - Changes to the final sentence of the second paragraph ("of the" was repeated twice): "The returned bytes are added to an **ArrayBuffer** and then appended to the **S**ourceBuffer which in turn is used as the SRC parameter of the HTML5 _video_ tag/element."

2. Section 2.10.2 suggestions:
  - Unsure whether to use "have" or "has" in the first sentence after "Some content [have/has]..."
  - The first paragraph could be condensed and merged into the second paragraph.  An intro sentence indicating that DRM exists to protect content during distribution to the end user while HDCP exists to prevent interception between the device and the display.
  - In the second paragraph, add a comma after this clause "If implemented by a device manufacturer,".  I'd also replace "it" with "HDCP":  "If implemented by a device manufacturer, HDCP..."
  - Be consistent and use client or device.
  - Last two sentences could be changes to something like: "If the exchange fails **,** the signal is **not transmitted to the display** and the device is **responsible for notifying the end user of the error**."
  - If the previous suggestion is not used, change "altering" to "alerting".

3. Section 2.10.3 suggestions:
  - Change "vendors SDK" to "vendor's  SDK".
  - Update "...provided by the vendor of this technology if to monitor..." to something like "...provided by the **watermarking** vendor **is** to monitor..."
  - Change "...intercepted screened..." to "...intercepted **and** screened...."
  - Change "If a suspect stream is found they then direct the service providers to the location where the streams have been misappropriated." to something like "If a suspect stream is found **the vendor directs** the service provider(s) to the **source of the misappropriated stream**."
  - Generally, I would suggesting using while instead of whilst.  I'm assuming US english is preferred over UK english for this document.
  - In the second paragraph, I want to clarify the "issue".  Maybe something like "**While watermarking** is not an issue that developers will often be faced with, **the processing requirements** can dictate the choice of platform for the content distribution."
  - The second sentence could be changed slightly: "The watermarking process requires processing power and low-level functionality through ring-fenced resources that platforms such as Android, iOS or Roku provide."

**Comment by thasso** [comment]
PR #74 integrates this feedback

**Comment by joelkorpi** [comment]
@thasso I'm going to close this one out! There were no further questions on the call today regarding this issue.
