### ISSUE TITLE
Add references to terms defined in the Glossary

### ISSUE THREAD

**Issue by tidoust** [w3c/webmediaguidelines#53]
It is good practice to link back to the definition of a term whenever it gets used in the document. ReSpec makes that easy with the use of `<dfn>` and href-less `<a>` (see [Definitions and Linking](https://github.com/w3c/respec/wiki/User's-Guide#definitions-and-linking) in ReSpec's documentation).

Although easy, it does require some initial editorial work and a little bit of discipline afterwards. The initial work is rather tedious, but I'm used to doing it, so I'd be happy to take a first pass at the document and insert the right markup, once the first batch of comments has been addressed (#46, #47, #49, #52).

Note the need for a bit of discipline would remain on the editors' shoulders. It's really not much work in practice, and experience suggests that it greatly helps with editing as it makes it easier to identify terms that are not properly defined and write a more consistent document.

**Comment by joelkorpi** [comment]
Pushed my commit with the top-half glossary complete @thasso https://github.com/w3c/webmediaguidelines/pull/79
