### ISSUE TITLE
Client Side Ads Insertion - Live Streaming - In-Stream metadata

### ISSUE THREAD

**Issue by epiclabsDASH** [w3c/webmediaguidelines#55]
One more point that I would like to bring to the table regarding CSAI and live streaming based on my experience.

Regarding live scenario (3.3.1), the most common use case I have seen is not related with using websockets but with using in-stream metadata (ex: using ID3 in HLS). This allows to trigger ads in all users at the same time and synced with the content. 

Typically broadcasters use SCTE-104/35 in their contribution workflows (SDI or transport stream based) to signal ads. When preparing the content to be distributed through Internet these SCTE-104/35 signals are usually "converted" to ID3/EMSG messages for HLS/DASH respectively. This keeps the media workflow for live ads insertion easy (SCTE to ID3/EMSG conversion is supported by most of encoders/media servers used by live content generators), is easy to consume from media players (most of players support parsing ID3/EMSG metadata), ensures synchronization with the content and avoids the need of using alternative communication channels like websocket that add complexity to the solution.

**Comment by joelkorpi** [comment]
Thanks for the feedback @epiclabsDASH ! I cleaned up this section a bit to incorporate some of your feedback. Please review: https://github.com/w3c/webmediaguidelines/pull/75

**Comment by mavgit** [comment]
Suggested in the call to change "Typically broadcasters..." to "Many broadcasters...", since "typically" implies a majority of worldwide broadcasters and we don't know that.
