### ISSUE TITLE
Server Side Ad Insertion - Events Triggering

### ISSUE THREAD

**Issue by epiclabsDASH** [w3c/webmediaguidelines#56]
> Where the player usually receives dedicated events in CSAI such as 'adStarted' or 'adEnded', Server-side insertions require a different setup to trigger such events. Typically, in-band notification are used to trigger time based events. For example, SCTE-35 markers are a common format to insert time based meta-data into the feed. These markers are read and interpreted by the player and can be used to trigger events or carry additional meta-data such as callback URLs.

Don't understand very well some of the context here. SSAI solutions that I have evaluated use SCTE-35 markers but just in the server side and as a way of triggering the insertion of ads. This ad insertion mechanism should be transparent to the player and those markers don't need to be interpreted by the player. 

Given said this, what I have seen is SSAI solutions, based on markers read in the server side and the ads inserted, are adding information to the stream (ex: Google DAI solution signals ads inserted in the HLS m3u8) that I guess are used for tracking/analytics purposes (player reporting when it is playing an ad, ad playback progress, etc).

**Comment by thasso** [comment]
I think SCTE-35 markers (and others) are still valid on the client side, i.e the player. They might be needed for tracking purposes, but they are also required for UI modifications on the player. For example, a common use-case would be to disable seeking while an Ad is playing. So I think it is still valid to expect and handle some sort of trigger.

@epiclabsDASH I am proposing to close this issue unless you have more concerns or a proposal how we could clarify the text.
