### ISSUE TITLE
Rendition configuration examples in 4.2 should be more clearly fictional

### ISSUE THREAD

**Issue by sandersaares** [w3c/webmediaguidelines#57]
I assume the point of the rendition parameters table in 4.2 is to illustrate the choices that must be made.

To avoid readers misinterpreting this as some sort of "best practices" table, it should be more clearly made imaginary. Instead of referencing HEVC and H.264, it should be changed to say "codec A" and "codec B". Perhaps the headers should also say "Example bitrates" and "Example framerates" to make its nature even more obvious. The 480p HEVC comment in the table should also be made more fictional.

This table should not drive (even by accident) decisions in projects related to selecting such parameters.

**Comment by joelkorpi** [comment]
Updated spec per your comments @sandersaares in PR #76
