### ISSUE TITLE
Describe live streaming resilience issues

### ISSUE THREAD

**Issue by sandersaares** [w3c/webmediaguidelines#58]
A common problem I see with live streaming in players is that missing data tends to completely crash the player and stop playback.

This can happen more easily in low latency scenarios, where a segment may need to be dropped due to temporary buffer fullness or network glitches. In such a scenario, it may be that segment N of a particular quality level is missing, while segment N of other quality levels is present. In some cases, segment N might be missing from all quality levels.

Different players have different approaches here - some just "jump the gap", whereas others might try another quality level. Assuming they can even tolerate such a failure (many treat it as a fatal error and just stop!).

I believe this is a common issue important enough to outline in the 2.11.4 "Potential Issues" chapter.

**Comment by epiclabsDASH** [comment]
Something to add: this same problem is also found in streams with timestamp alignment issues or with timestamp discontinuities (these two cases apply to both VOD and live). 

Although in most of cases this type of issues are raising an encoding issue, in the video player implementation is always good to have a mechanism to jump those short timestamp gaps and increase playback resilience.

**Comment by thasso** [comment]
I created PR #77
