### ISSUE TITLE
3.2 seems oddly Widevine specific

### ISSUE THREAD

**Issue by sandersaares** [w3c/webmediaguidelines#59]
The section mentions Widevine rather a lot and seems to base much of its content on how Widevine works. It should be worded in a more DRM-neutral fashion and be refactored to be more universal.

**Comment by bwidtmann** [comment]
maybe you replace "Widevine" with "CDM"

**Comment by thasso** [comment]
I removed the very Widevine specific paragraph in PR #73. That should make it more generic and imo that paragraph was not really needed in this section.
