### ISSUE TITLE
3.2 is misleading in terms of how DRM activation occurs

### ISSUE THREAD

**Issue by sandersaares** [w3c/webmediaguidelines#60]
EME says that the "encrypted" event is simply a signal that initData was found in the media stream. Encrypted media can be consumed without ever containing initData in the media stream (e.g. when it is supplied externally) the description in 3.2 is misleading as it gives the impression that the "encrypted" event is a necessary part of the flow.

**Comment by thasso** [comment]
I added PR #78 to clarify that the encrypted event is not mandatory
