### ISSUE TITLE
Guidelines for 'emsg' in Type 3 players

### ISSUE THREAD

**Issue by johnluther** [w3c/webmediaguidelines#64]
In the November 7 WAVE HATF call, it was suggested that this action item from October 2nd should have a Github Issue to track it:

"HATF Developer Guidelines spec to add guidelines for Type 3 players on extracting, processing, expressing and acting on emsg boxes with guidance for implementation."

See this WAVE thread for some background: https://standards.cta.tech/apps/org/workgroup/wtwg/email/archives/201709/msg00027.html

**Comment by KilroyHughes** [comment]
The whitepaper overview on CMAF/DASH Event Messages was posted to HATF Kavi:
https://standards.cta.tech/apps/org/workgroup/hatf/download.php/22166/Event%20Messages%20in%20WAVE.docx
The main conclusion of its review at the CES F2F meeting was that W3C Data Cue Tracks would be very useful in communicating Event Messages from the media parser in the user agent to HTML5 applications that usually consume these events.

Type 3 players, such as DASH.js, can parse an Event Message Box in script that has been prepended to the start of a Media Segment they have download, but aren't expected to deep parse Segments to find Event Message Boxes that may have been prepended to an (optional) CMAF Chunks within a Segment. Platforms always do deep parsing in native code to decode Media Segments, so sending a Data Cue to the Web app that will use it for display or control would improve efficiency and capability.
