### ISSUE TITLE
Add a section on Media Capability Discovery

### ISSUE THREAD

**Issue by mavgit** [w3c/webmediaguidelines#66]
The December 18, 2017 TWG call asked that the Developer Guidelines add a section on media capability discovery, e.g.:
- HTML spec API [HTMLMediaElement.canPlayType()](https://www.w3.org/TR/html51/single-page.html#the-media-elements)
- MSE spec API [MediaSource.isTypeSupported()](https://www.w3.org/TR/media-source/#methods)

**Comment by thasso** [comment]
I will add a paragraph about this.
