### ISSUE TITLE
Thumbnails support in DASH

### ISSUE THREAD

**Issue by epiclabsDASH** [w3c/webmediaguidelines#67]
> Unfortunately, neither DASH or HLS do currently specify a way to reference thumbnail images directly from manifests. This however is certainly possible and there is already a proposal to add support for thumbnails to the DASH-IF guidelines [DASHIFIOP]. This would certainly simplify live playback case where the application has to update the information about thumbnails with each manifest update.

In the latest version of DASH-IF guidelines ([DASHIFIOP 4.1](http://dashif.org/wp-content/uploads/2017/09/DASH-IF-IOP-v4.1-clean.pdf)), the proposal regarding thumbnails support, valid for both live and vod streams, has been accepted and included (clause 3.2.9 and clause 6.2.6)

**Comment by thasso** [comment]
I updated the paragraph in PR #72 to reference DASH-IF and include an example.
