### ISSUE TITLE
Change Jeff Burtoft to Former Editor

### ISSUE THREAD

**Issue by mavgit** [w3c/webmediaguidelines#70]
I understand from an email thread that Jeff Burtoft is no longer an editor. Please update the Editors section with a note that Jeff is a "Former Editor".

I understand the Respect syntax is shown [here](https://github.com/w3c/remote-playback/pull/96/commits/75b269e896b76d3279e7b5aa94d13760c737a7d0)

**Comment by joelkorpi** [comment]
Done!
