### ISSUE TITLE
recomendations for shaping document

### ISSUE THREAD

**Issue by boyofgreen** [w3c/webmediaguidelines#8]
On the Editor's call this morning, we talked a bit about the direction of the document, and wanted to get the full consensus of the team.  Thasso brought up a good point that most developers will be approaching media content from a player perspective.  The content as we have it now basically teaches that how to build a player from scratch, which is probably not reasonable or desirable for most developers.  We had thought about gearing the content to better help developers understand and troubleshoot what is going on in the player.  The recommendation is:
 - remove section 5.  This example code would most likely be using a player or pulled from a player, and the content it is discussing is all explained in the previous sections.
- add code snippets within the explanations to understand what players are doing to achieve each feature.   this could would be code you can copy and past into a window and run, but it should help troubleshoot.
- Gear content towards high level understanding (like section 2.1 is now) so developers can better interact with the player code and content creators.
  Thoughts?

**Comment by mavgit** [comment]
Thanks for the notes. Sorry I had a conflict & had to miss it.

This discussion brings up a question to me: Should WAVE be trying to standardize the interface between applications and players?

Thanks,
mav

**Comment by boyofgreen** [comment]
Good question.  What would something like that look like?  Would this be an API layer or sorts that would sit on top of the players (kinda like a cordova style API layer?). This wouldn't be my first thought.

**Comment by joelkorpi** [comment]
I'm fine with removing section 5.
