### ISSUE TITLE
DRM in "Content Playback" section

### ISSUE THREAD

**Issue by johnluther** [w3c/webmediaguidelines#80]
The steps assume DRM'd content. I'm not sure how relevant DRM here since the section is explaining general ABR playback principals. 

Also, technically it is not the player that performs license key request creation and content decryption, it is the CDM.

**Comment by joelkorpi** [comment]
Which section are you referring to @johnluther ?

**Comment by johnluther** [comment]
Oops, sorry. Section 2.4.

**Comment by joelkorpi** [comment]
We suggest removing bullet #1 and #5 and adding a note below saying "steps will differ if DRM is used"

**Comment by joelkorpi** [comment]
This issue has been resolved in PR #88
