### ISSUE TITLE
Manifests and URLs in section 2.3 Content Delivery

### ISSUE THREAD

**Issue by paulhiggs** [w3c/webmediaguidelines#81]
The second paragraph says this 

> The manifest is typically passed to a player. The player makes a HTTP GET request for the manifest from CDN edge, the edge server's location is determined via DNS.

If the manifest is passed to the player, then the player should not have to retrieve the manifest again. In light of this paragraph, it may be corrected to 

> At this stage, the control in the chain switches to the client's web video application. The content provider supplies the client with the URL of a manifest file located on a CDN rather than the origin. The manifest **_URL_** is typically passed to a player. The player makes a HTTP GET request for the manifest from CDN edge, the edge server's location is determined via DNS. If the CDN edge does not currently have the manifest available, the CDN requests a copy of the file from the origin and the file is cached within the server for later use. There are different levels of caching; popular VOD content is kept closer to the edge in the CDN network in this way it can be delivered to customers faster than an edge server that isn't tuned for high volume delivery. The CDN edge then returns the the manifest to the requesting player.

The difference between the "origin" and "CDN" is difficult to determine in this paragraph. It is quite likely that the manifest URL is to the actual origin where the manifest is created. The CDN may use some other techniques to provide that manifest to the client, but often the CDN architecture (node names, IP addresses, request redirections) should be unknown to the client

**Comment by joelkorpi** [comment]
Thank you Paul. This issue was addressed in PR #89
