### ISSUE TITLE
Section 2.4 Content Playback item 2

### ISSUE THREAD

**Issue by paulhiggs** [w3c/webmediaguidelines#82]
Bullet #2 says
> The player's ABR algorithm determines the data throughput rate available to the client by calculating the throughput from the first segment of video. This provides enough information to determine the initial playback quality level the player can sustain.

This does not answer the question as to what playback quality is selected by the client for retrieving the first video segment. This is typically a client based algorithm, we could have a note on this point to ensure completeness

**Comment by thasso** [comment]
I agree and will add something to clarify

**Comment by thasso** [comment]
I added PR #93 to address this.
