### ISSUE TITLE
Section 2.4 Content Playback, item #6

### ISSUE THREAD

**Issue by paulhiggs** [w3c/webmediaguidelines#83]
Item 6 says
> It then adds it to the player's video buffer.

Since this entire section is about the player behavior, it may be better just to say 
_It then adds the decrypted segment to the  video buffer._

**Comment by thasso** [comment]
I will check that item, though I think what it should refer to is the Media Source Buffer and we are adding segments, but not necessarily decrypted segments. In case of encrypted/DRM protected content, the CDM will decrypt before or while the data is being pushed towards the decoder, but technically I think the Media Source Buffer does not contain decrypted content. But I will for sure add information about the segment so its clear what data is pushed and where.

**Comment by thasso** [comment]
I added PR #94 that rewrite that item and hopefully clarifies what happens to the downloaded segment.
