### ISSUE TITLE
Headings in section 2

### ISSUE THREAD

**Issue by paulhiggs** [w3c/webmediaguidelines#85]
The current headings are 

>2. Media Playback Use Cases
2.1 General Description
2.2 Content Generation
2.3 Content Delivery
2.4 Content Playback
2.5 On-Demand Streaming (VOD)
2.6 Content Generation
2.7 Content Delivery
2.8 Content Playback
2.9 VOD Pre-caching

It seems that 

-  2.2, 2.3 and 2.4 should be sub headings under _2.1 General Description_
-  2.6, 2.7, 2.8 and 2.9 should be sub headings under _2.5 On-Demand Streaming (VOD)_

**Comment by joelkorpi** [comment]
I will update this according to your feedback

**Comment by joelkorpi** [comment]
This was updated per comments in a recent release
