### ISSUE TITLE
Formal reference to DASH-IF Guidelines

### ISSUE THREAD

**Issue by paulhiggs** [w3c/webmediaguidelines#86]
Section 2.12 identified the `thumbnail_tile` as being defined in v3,0 of the DASH-IF guidelines.
Annex A refers to version 3.0 of the DASH-IF Guidelines.

This functionality was first published in v4.1 of the DASH-IF Guidelines.

The most recent version of the DASH-IF Guidelines is v4.2 (https://dashif.org/wp-content/uploads/2018/04/DASH-IF-IOP-v4.2-clean.pdf)

**Comment by thasso** [comment]
I will update the reference and link to v4.2

**Comment by thasso** [comment]
PR #92 addresses this. Unfortunatley I could not find a reference to the latest DASH-IF IOP
guidelines in refspec. Instead I replaced the reference with a link to the 4.2 guideline specs.

**Comment by thasso** [comment]
I submitted a PR (https://github.com/tobie/specref/pull/482) to specref to get the DASHIF version update there. If that goes through I will change the link back to the specref version.

**Comment by mavgit** [comment]
Thasso,

Nice job! SpecRef now references v4.2!!
                https://github.com/tobie/specref/pull/482/commits/c6370ec29cfa024cfb7a4d38d610d7a15b2b7388

…and the beauty of SpecRef is you get the updated reference without modifying your spec! ☺ (I checked.)

**Comment by thasso** [comment]
Since specref is updated I propose to not update/merge the PR but just close this issue.

**Comment by mavgit** [comment]
I agree with just closing the issue.
