### ISSUE TITLE
Use of unique device identifiers

### ISSUE THREAD

**Issue by paulhiggs** [w3c/webmediaguidelines#87]
Section 3.1.2 gives some information about how unique device identifiers can be created but the specification does not seem to make any use of them.
While this paragraph is interesting, it would be useful to give a few examples of where the unique device identifier could be used and what impacts the application developer needs to consider.

**Comment by thasso** [comment]
I think its a good point and I will take a look at section 3.1 in general and that specific paragraph. Right now I'm thinking of re-writing that to make clear that the device identification is primarily related to DRM and its internals and is in fact not suppose to leak out if that black box. I think the intention of Web API's is in fact the opposite and is intended to prevent easy device identification.

**Comment by joelkorpi** [comment]
I will move section 3.3 into it's own section for Advertising as part of this.

**Comment by thasso** [comment]
I added PR #96 that adds some examples.
