### ISSUE TITLE
section 2.2 - VOD use cases

### ISSUE THREAD

**Issue by edwardmhunton** [w3c/webmediaguidelines#9]
These are some topics that came out a discussion on VOD specific use cases here at Sky:

- Pre-caching vod
- Device storage / local storage
- Late binding Audio switching tracks (up to 12) live and vod
- Bitrate capping
- Buffer manipulation (device / storage dependant)
- Vod assets remain at the edge longer
- President unique ID exposed via js - signed code issue
- HTTP byte range requests
- HTTPs support
- Player event exposure
- HDCP security requirement for HDMI
- GSMA flag at DRM rights
- Water marking
- Hardware acceleration support

I can get something down for these but wont be able to provide MSE/JS examples.

**Comment by boyofgreen** [comment]
I would suggest to get them in the outline at the appropriate places, then we will look for volunteers to build out the examples.  Note, we are discussion removing section 5 and merging code samples or snipits into the documentation sections.

**Comment by edwardmhunton** [comment]
I have written content for 

- Pre-caching vod
- Device storage / local storage

but need to proof read / edit before pushing

**Comment by thasso** [comment]
Since this is already merged with PR #12, I am closing.
