### ISSUE TITLE
Remove "2018" from title.

### ISSUE THREAD

**Issue by mavgit** [w3c/webmediaguidelines#98]
As discussed in the Steering Committee last week, we should remove "2018" from the title of the developer spec, for a few reasons:
1. This is not a spec that needs to be updated every year, like the API Snapshot spec does.
2. It's taken a lot more time to complete this spec than originally expected and we are unlikely to publish an updated version in a year.
3. The prominent "2018" date will make the spec seem out of date very soon after publishing in December, when in less than a month it will be 2019!

This reverses #48.

**Comment by thasso** [comment]
This is addressed in PR #100
